### ISSUE TITLE
ABC videos not playing 

### ISSUE THREAD

**Issue by jpadhye** [plexinc-plugins/ABC.bundle#21]
```
2016-10-02 19:06:16,257 (7f7ddf7fe700) :  DEBUG (runtime:717) - Handling request GET /video/abc/season?id=SH551883122&title=Quantico
2016-10-02 19:06:16,259 (7f7ddf7fe700) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2016-10-02 19:06:16,260 (7f7ddf7fe700) :  DEBUG (runtime:814) - Found route matching /video/abc/season
2016-10-02 19:06:16,263 (7f7ddf7fe700) :  DEBUG (networking:161) - Fetching 'https://api.pluto.watchabc.go.com/api/ws/pluto/v1/layout?brand=001&device=002&type=show&show=SH551883122' from the HTTP cache
2016-10-02 19:06:16,267 (7f7ddf7fe700) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2016-10-02 19:06:16,267 (7f7ddf7fe700) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 498 bytes
2016-10-02 19:06:16,300 (7f7ddf7fe700) :  DEBUG (runtime:717) - Handling request GET /video/abc/episodes?season=2&id=SH551883122&title=Quantico
2016-10-02 19:06:16,302 (7f7ddf7fe700) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2016-10-02 19:06:16,303 (7f7ddf7fe700) :  DEBUG (runtime:814) - Found route matching /video/abc/episodes
2016-10-02 19:06:16,306 (7f7ddf7fe700) :  DEBUG (networking:161) - Fetching 'https://api.pluto.watchabc.go.com/api/ws/pluto/v1/module/tilegroup/1925878?brand=001&device=002&show=SH551883122&season=2&start=0&size=50' from the HTTP cache
2016-10-02 19:06:16,311 (7f7ddf7fe700) :  DEBUG (services:603) - No service found for URL 'abc://VDKA3400790'
2016-10-02 19:06:16,312 (7f7ddf7fe700) :  DEBUG (services:618) - No matching services found for 'abc://VDKA3400790'
2016-10-02 19:06:16,313 (7f7ddf7fe700) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2016-10-02 19:06:16,316 (7f7ddf7fe700) :  DEBUG (services:603) - No service found for URL 'abc://VDKA3400790'
2016-10-02 19:06:16,316 (7f7ddf7fe700) :  CRITICAL (runtime:970) - Exception when constructing response (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 951, in construct_response
    el = result._to_xml()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/objectkit.py", line 667, in _to_xml
    el = Framework.modelling.objects.ModelInterfaceObjectContainer._to_xml(self)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling/objects.py", line 382, in _to_xml
    root = Container._to_xml(self)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling/objects.py", line 139, in _to_xml
    self._append_children(root, self._objects)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling/objects.py", line 145, in _append_children
    el = obj._to_xml()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/objectkit.py", line 580, in _to_xml
    if self._core.services.function_in_service_is_deferred(Framework.components.services.MEDIA_OBJECTS_FUNCTION_NAME, service):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/services.py", line 557, in function_in_service_is_deferred
    service.sandbox.context.import_values(values)
AttributeError: 'NoneType' object has no attribute 'sandbox'

2016-10-02 19:06:16,316 (7f7ddf7fe700) :  DEBUG (runtime:1027) - Unable to handle response type: <class 'Framework.modelling.objects.MediaContainer'>
2016-10-02 19:06:16,317 (7f7ddf7fe700) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2016-10-02 19:06:16,317 (7f7ddf7fe700) :  DEBUG (runtime:924) - Response: [500] MediaContainer, 0 bytes
```

**Comment by sander1** [comment]
Make sure you have the latest Services bundle (Plex Media Server version 1+ will update this automatically). This issue has been fixed in https://github.com/plexinc-plugins/Services.bundle/commit/0d3fd7f0b86a90ce934daa7e720db77df0a21dd7#diff-4b90d449b3cc458eaba0048a1004c2db

**Comment by jpadhye** [comment]
@sander1 I pulled the latest code yesterday. My plex version is Version 1.1.4.2757. I'm still seeing the same error today. There are some more logs generated.

2016-10-02 19:24:23,021 (7f7ddf7fe700) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 25472 bytes
2016-10-02 19:24:46,918 (7f7ddf7fe700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.plugins.abc/reloadServices
2016-10-02 19:24:46,922 (7f7ddf7fe700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.plugins.abc/reloadServices
2016-10-02 19:24:46,923 (7f7ddf7fe700) :  DEBUG (services:15) - Reloading services
2016-10-02 19:24:46,924 (7f7ddf7fe700) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2016-10-02 19:24:46,925 (7f7ddf7fe700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2016-10-02 19:24:47,103 (7f7ddf7fe700) :  DEBUG (services:362) - Loaded services
2016-10-02 19:24:47,104 (7f7ddf7fe700) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2016-10-02 19:24:47,104 (7f7ddf7fe700) :  DEBUG (runtime:924) - Response: [200] bool, 0 bytes
2016-10-02 19:26:32,028 (7f7ddf7fe700) :  DEBUG (runtime:717) - Handling request GET /video/abc
2016-10-02 19:26:32,032 (7f7ddf7fe700) :  DEBUG (runtime:814) - Found route matching /video/abc
2016-10-02 19:26:32,036 (7f7ddf7fe700) :  DEBUG (networking:161) - Fetching 'https://api.pluto.watchabc.go.com/api/ws/pluto/v1/module/tilegroup/1389461?brand=001&device=002&start=0&size=100' from the HTTP cache
2016-10-02 19:26:32,049 (7f7ddf7fe700) :  DEBUG (base:117) - Checking if com.plexapp.plugins.abc is broken
2016-10-02 19:26:32,050 (7f7ddf7fe700) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjMKY29tLnBsZXhhcHAucGx1Z2lucy5hYmNzMTAKaWRlbnRpZmllcnIwCg__'
2016-10-02 19:26:32,090 (7f7ddf7fe700) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2016-10-02 19:26:32,090 (7f7ddf7fe700) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 25472 bytes

**Comment by jpadhye** [comment]
@sander1 Please let me know the steps if you need more logs. More details about my setup. I'm running PMS on Ubuntu 14 LTS. The client is Roku App and Chrome browser
